name: Swift Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        swift: ["6.0.0"]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: ${{ matrix.swift }}
    
    - name: Get Swift version
      run: swift --version
      
    - name: Build
      run: swift build
      
    - name: Run tests
      run: swift test
      
    # Performance test
    - name: Run performance tests
      if: ${{ matrix.os == 'macos-latest' }}
      run: swift test -c release